name: FINE
model: fine
# pth: /home/myr/these/datasets
pth: /etudiants/siscol/t/themyr_l/US

inference:
  path: ${model.pth}/${model.name}

checkpoint:
  save: 1
  load: False
  load_path: ${pth}/${model.name}/checkpoint/latest.pt
  path: ${pth}/${model.name}/checkpoint